# Generated by Django 4.2.27 on 2026-01-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='assignments_completed',
            field=models.FloatField(default=0),
        ),
    ]
